=== Lalitho14/AdopcionAP/Admin/adopciones.dtd
<!ELEMENT Adopciones (Adopcion*)>
<!ELEMENT Adopcion (id, fecha, mascota, duenio)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT mascota (id_Mascota, nombre, tipo, descripcion, adoptado, imagen)>
<!ELEMENT id_Mascota (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT adoptado (#PCDATA)>
<!ELEMENT imagen (#PCDATA)>
<!ELEMENT duenio (id_Duenio, nombre, username, tipo)>
<!ELEMENT id_Duenio (#PCDATA)>
<!ELEMENT username (#PCDATA)>

=== Lalitho14/AdopcionAP/Admin/adopciones.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Adopciones SYSTEM "./adopciones.dtd">
<?xml-stylesheet type="text/xsl" href="./Veterinaria.xsl"?>
<Adopciones>
  <Adopcion>
    <id>4</id>
    <fecha>2024-11-19 22:58:10</fecha>
    <mascota>
      <id_Mascota>3</id_Mascota>
      <nombre>Blu</nombre>
      <tipo>ave</tipo>
      <descripcion>Aparecio en la pelicula de Rio y Rio 2 no se que decir se ve fachero pero no lo conozco.</descripcion>
      <adoptado>0</adoptado>
      <imagen>ave03.jpg</imagen>
    </mascota>
    <duenio>
      <id_Duenio>2</id_Duenio>
      <nombre>Hugo</nombre>
      <username>Hugo</username>
      <tipo>1</tipo>
    </duenio>
  </Adopcion>
</Adopciones>
